generation:
  do_sample: true
  max_new_tokens: 512
  repetition_penalty: 1.2
  temperature: 0.7
  top_k: 20
  top_p: 0.8
lora:
  alpha: 32
  dropout: 0.1
  r: 16
  target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
model_name: Qwen/Qwen3-1.7B
training:
  batch_size: 4
  epochs: 3
  learning_rate: 5.0e-05
  max_length: 1024
